name: LobbySystem
author: TrenicHD
main: TrenicHD\Main
api: [3.0.0, 4.0.0]
version: 1.1.0
description: a LobbySystem by TrenicHD

commands:
  ls:
    description: §bLobbySystem Info

permissions:
  ls.use:
    default: true
  fly.use:
    default: op
  size.use:
    default: op
  inv.use:
    default: true
  speed.use:
    default: op
  time.use:
    default: op